apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omnia

resources:
  - ../../base

patches:
  - path: patches.yaml
    target:
      kind: IngressRoute
      name: omnia
  - path: deployment-patches.yaml