apiVersion: apps/v1
kind: Deployment
metadata:
  name: omnia-api
  labels:
    app: omnia-api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: omnia-api
  template:
    metadata:
      labels:
        app: omnia-api
    spec:
      serviceAccountName: github-deployer
      containers:
        - name: api
          image: ghcr.io/rmurier/omnia-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: omnia-app-secrets
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:8080"
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: omnia-secrets
                  key: connection-string
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"