apiVersion: v1
kind: Service
metadata:
  name: front
  labels:
    app: omnia-front
spec:
  selector:
    app: omnia-front
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP