apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - db-service.yaml
  - db-statefulset.yaml
  - api-service.yaml
  - api-deployment.yaml
  - front-service.yaml
  - front-deployment.yaml
  - ingress-route.yaml