apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-deployer-binding
subjects:
  - kind: ServiceAccount
    name: github-deployer
roleRef:
  kind: Role
  name: github-deployer-role
  apiGroup: rbac.authorization.k8s.io
